### ISSUE TITLE
Running action failed

### ISSUE THREAD

**Issue by bigdargon** [dead-hosts/dev-center#23]
After the Action configuration was updated in the template, I tried creating a new repo with my account https://github.com/bigdargon/hostsVN-dead-hosts. When changing the info file, the Action works normally ([Link](https://github.com/bigdargon/hostsVN-dead-hosts/actions/runs/1944097811)), but then it fails ([Link](https://github.com/bigdargon/hostsVN-dead-hosts/actions/runs/1944170769)).

Log
```
Fatal Error: substring not found
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 990, in start
    self.stop_and_wait_for_all_manager()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 927, in stop_and_wait_for_all_manager
    self.tester_process_manager.wait()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/PyFunceble/cli/processes/base.py", line 330, in wait
    raise worker_error
ValueError: substring not found

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/bin/dead-hosts-launcher", line 8, in <module>
    sys.exit(tool())
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/dead_hosts/launcher/cli.py", line 106, in tool
    Orchestration(end=arguments.end, save=arguments.save)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/dead_hosts/launcher/orchestration.py", line 118, in __init__
    self.run_test()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/dead_hosts/launcher/orchestration.py", line 217, in run_test
    Command(f"PyFunceble -f {self.origin_file.path}").run_to_stdout()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/PyFunceble/helpers/command.py", line 246, in run_to_stdout
    for line in self.run(rstrip=False):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/dead_hosts/launcher/command.py", line 76, in run
    raise RuntimeError(
RuntimeError: Something went wrong.

Error: Process completed with exit code 1.
```

So what do I do to fix it? Or have I configured something wrong somewhere? Please help me! Thank you!

**Comment by funilrys** [comment]
Hi @bigdargon, sorry for the waiting time. Do you have the following secrets declared:

```
GIT_NAME: "${{ secrets.GIT_BOT_NAME }}"
GIT_EMAIL: "${{ secrets.GIT_BOT_EMAIL }}"
GITHUB_TOKEN: "${{ secrets.BOT_REPO_PAT }}"
```

**Comment by funilrys** [comment]
- `GIT_BOT_NAME` (secret) should be your Git Name
- `GIT_BOT_EMAIL` (secret) should be your Git Email
- `GIT_REPO_PAT` (secret) should be an access token that is authorized to push inside the repository. 


@dead-hosts, they are declared globally at the organization level. You should be able to declare them at repository level too.

**Comment by bigdargon** [comment]
@funilrys Thank you for your reply! I have declared my secrets here

![Screenshot 2022-03-12 211551](https://user-images.githubusercontent.com/10969626/158021559-740e2775-26e0-44a3-8a9c-8ed474baf7d7.png)

Personal access tokens I have set the permissions as follows

![Screenshot 2022-03-12 211942](https://user-images.githubusercontent.com/10969626/158021615-08622714-17f0-4990-8055-3dd94f7b593a.png)

**Comment by funilrys** [comment]
Delete the content of `.pyfunceble/***` and create a new file called `.pyfunceble/.gitkeep`... Let's see how it goes ...

**Comment by funilrys** [comment]
By the way, if you don't want or need the special features of the @dead-hosts infrastructure, you may inspire yourself from: https://github.com/PyFunceble/ci_test 

It's running every few hours and it's working 😉

**Comment by funilrys** [comment]
cc @bigdargon

**Comment by bigdargon** [comment]
> Delete the content of `.pyfunceble/***` and create a new file called `.pyfunceble/.gitkeep`... Let's see how it goes ...

@funilrys I did the above way, but still failed! https://github.com/bigdargon/hostsVN-dead-hosts/actions/runs/1975931308

```
vitpc.yadro.ru                                                                                       ACTIVE      DNSLOOKUP  Unknown           Unknown                        Unknown    AVAILABILITY 
Fatal Error: substring not found
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 990, in start
    self.stop_and_wait_for_all_manager()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/PyFunceble/cli/system/launcher.py", line 927, in stop_and_wait_for_all_manager
    self.tester_process_manager.wait()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/PyFunceble/cli/processes/base.py", line 330, in wait
    raise worker_error
ValueError: substring not found

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/bin/dead-hosts-launcher", line 8, in <module>
    sys.exit(tool())
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/dead_hosts/launcher/cli.py", line 106, in tool
    Orchestration(end=arguments.end, save=arguments.save)
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/dead_hosts/launcher/orchestration.py", line 118, in __init__
    self.run_test()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/dead_hosts/launcher/orchestration.py", line 217, in run_test
    Command(f"PyFunceble -f {self.origin_file.path}").run_to_stdout()
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/PyFunceble/helpers/command.py", line 246, in run_to_stdout
    for line in self.run(rstrip=False):
  File "/opt/hostedtoolcache/Python/3.9.1/x64/lib/python3.9/site-packages/dead_hosts/launcher/command.py", line 76, in run
    raise RuntimeError(
RuntimeError: Something went wrong.

Error: Process completed with exit code 1.
```

**Comment by funilrys** [comment]
I'm experimenting through: https://github.com/funilrys/dead-hosts-outside-test . I'll come back to you with the solution - as soon as I have it.

**Comment by funilrys** [comment]
Well @bigdargon it seems to work out there.

**Comment by funilrys** [comment]
@bigdargon, you can see the change in the GIT history ... But here are the ONLY secret I added:

![image](https://user-images.githubusercontent.com/14127285/158268682-4d67ed64-1da0-4a7e-b3f4-145a2f4580ad.png)

....

**Comment by bigdargon** [comment]
> I'm experimenting through: https://github.com/funilrys/dead-hosts-outside-test . I'll come back to you with the solution - as soon as I have it.

Thanks you!


> Well @bigdargon it seems to work out there.

I followed the repo! The first action when editing the info file works fine, i will try creating another repo to test!

**Comment by bigdargon** [comment]
@funilrys Looks like the Action still fails.

**Comment by funilrys** [comment]
@bigdargon yup saw that. funilrys/PyFunceble#297 is actually the issue that enlighten what's going on ...
Sorry for the time to wait ... I have a lot to deal with right now ... 

It should be fixed with the next version of the `PyFunceble-dev` package.
